### PR TITLE
fix: Allow for chaining multiple displays

### PR DESCRIPTION
**Pull request by chrissearle**
I wanted to have two of the 4 screen displays chained. This change moves the number of vertical and horizontal to settings and then does the initialization of position and rotation based on the numbers rather than a fixed number of times.

### CODE REVIEW

**Comment by Qrome** [comment]
Chris, thanks for the contribution.   I have already started this implementation last week and it can be found in the 2.0 dev branch here:  https://github.com/Qrome/marquee-scroller/compare/2.0

Would you mind testing that out and see if it will work for you?

**Comment by Qrome** [comment]
After looking over this implementation, I think I like the dynamic building of the matrix settings.   Very nice.    I will look at getting this in the 2.0 release.

**Comment by chrissearle** [comment]
In the loop I've assumed a single row - the rotation stuff would also work if you had 4x2 or similar - but the position stuff doesn't. However - single row seems most relevant here (at least for me) :)

**Comment by Qrome** [comment]
I created a new PR from your branch against the 2.0dev branch and have merged it there.   Thanks for the contribution.

**Pull request closed without merging**
