### PR TITLE
added pm indicator, and changed to a simplified time client with buil…

### PR DESCRIPTION
**Pull request by magnum129**
added pm indicator, and changed to a simplified time client with buitin dst, but it requires another, free, api key...

Don't know if you're interested...

I may have broken the new octoprint indicator too... haven't had a chance to test.

### CODE REVIEW

**Comment by Qrome** [comment]
I have created a release target branch for 2.10 and I will pull this in there.   From looking it over, I like it.   I like the idea of getting away from GeoNames API.   I will run it for a few days on a clock and check it out.

**Comment by Qrome** [comment]
I have pulled this in the v2.10 release branch for testing.   I have updated the branch with changes including the UI toggle for turning on and off the PM indicator.   For some reason it wasn't working for me.   I am happy about dropping GeoNames as well as picking up the DST changes provided by the time TimeZoneDB service.   I will be testing it a bit more, but I think this will go in soon.

Can you please pull down the 2.10 release branch and test it as well?   Thanks!

**Comment by magnum129** [comment]
I pulled it and am running it on mine. Are you running a wide version, or the normal version? I can only test the pm indicator on the normal version.

**Comment by Qrome** [comment]
I have both, I will test the wide version now.

**Comment by Qrome** [comment]
Yep, it puts it in the right spot.

**Comment by magnum129** [comment]
Cool, thank you for testing that! I've still got to test the octoprint
status. I messed with it, to try to get rid of the flicker. I'm pretty sure
it won't help. Anything beyond the first display.write seems to flicker. I
might mess with the center print function to make it handle all of the
options with a single write to maybe eliminate flicker.

**Comment by Qrome** [comment]
Sounds good.   Thanks again for following the patterns in the project.   Nice addition the TimeDB class.   I have just updated the V2.10 release with a few more items.
* Warning to configure TimeZone DB if key is empty
* Added "Very Fast" scroll speed for wide screen displays

**Comment by magnum129** [comment]
Good call, on the notice, since it's a breaking change.

I think I figured out the flicker too, I just modified the centerPrint
function. Seems to have cleared it up. Not worth a merge request though, if
you don't mind putting it in... Just need to modify the uses of the center
print function to pass false except the   centerPrint(currentTime,true);

void centerPrint(String msg, bool extraStuff) {
  int x = (matrix.width() - (msg.length() * width)) / 2;
  matrix.setCursor(x, 0);
  matrix.print(msg);
  if (extraStuff) {

    if (!IS_24HOUR && IS_PM) {
      matrix.drawChar(matrix.width() - 4, 0, '.', HIGH, LOW, 1);
    }

    if (OCTOPRINT_ENABLED && OCTOPRINT_PROGRESS &&
printerClient.isPrinting()) {
      int numberOfLightPixels =
(printerClient.getProgressCompletion().toFloat() / float(100)) *
(matrix.width() - 1);
      matrix.drawFastHLine(0, 7, numberOfLightPixels, HIGH);
    }
  }

  matrix.write();
}

I can submit a MR tomorrow, if you'd still like one.

**Comment by Qrome** [comment]
That works perfectly.   I added an overload for the centerPrint function so it can be called both ways.   This looks great.  I will push up my changes to the 2.10 very soon.  Need to compile the binary files.

**Comment by Qrome** [comment]
Ok, updated the 2.10 -- have a look when you can.   Thanks.

**Pull request merged**
